# TST Credentials (Base64 encoded)

# Password: Welcome@126
username=SXNiYV9UZXN0QGFjY2VudHVyZS5jb20=
password=UXdlcnR5QDEzNiM=

TOKEN_URL=https://test-login.origincrossmedia.com/oauth/token
CLIENT_ID=jEEsCZFrCR5cdemcQc6ORQPkZMoJmM8y
CLIENT_SECRET=vM8Jnm8L2HILZt86ZlyeHdxLNlxhpZudb8IVUIberLhuHgdokpGXsGQTzyJf1nt_
AUDIENCE=https://origin-tst
SCOPE=openid
ENCODED_EMAIL=SXNiYV9UZXN0QGFjY2VudHVyZS5jb20=
ENCODED_PASSWORD=UXdlcnR5QDEzNiM=