# TST Environment - Origin
TST_UI_URL=https://test-cmm.origincrossmedia.com/
TST_API_URL=https://test-cmm.origincrossmedia.com/api

# STG Environment - Staging
STG_UI_URL=https://staging-cmm.origincrossmedia.com/
STG_API_URL=https://stg-cmm.origincrossmedia.com/api

# UAT Environment - Aquila
UAT_UI_URL=https://uat-cmm.origincrossmedia.com/
UAT_API_URL=https://uat-cmm.origincrossmedia.com/api

# Default Environment (change this to switch environments)
# Options: TST, STG, or UAT
DEFAULT_ENV=TST