BASE_URI=https://test-cmm.origincrossmedia.com/api

SearchWithFilter=/v2.5/campaign/search

CreateReport=/v2.5/report/createreport
SubmitReport=/v2.5/report/submit/{uuid}
getReportByMcid=/v2.5/report/searchreports/{mcId}


GetReportByPageNumber=/v2.5/report/searchreports/Ceq6zPONCi0
GetReportDetaisById=/v2.5/report/getbyid//{reportId}

CreateCampaign=/v2.5/campaigngroups
GetCampaignDetailsByCampaignId=/v2.5/campaigngroup/{campaignGroupId}
getCampaignByMcid=/v2.5/campaigngroups/measurementconsumers/{mcId}
getCampaignForDataProvider=/v2.5/campaigngroups/dataproviders
getMetricCalcSpecs=/v2.5/metricCalcSpecs





getReportByMC=/v2.5/report/searchreports/Ceq6zPONCi0
REPORT_PATH=/v2.5/report/searchreports/Ceq6zPONCi0
GetReportByPageNum=/v2.5/report/listreports/Ceq6zPONCi0/page/2?pagesize=50